version: '3'

services:
  cloudingairsql:
    container_name: cloudingair-reservations
    build:
      context: ./cloudingair-sql
      dockerfile: Dockerfile
    image: cloudingairsql:latest
    expose:
      - "8080"
    networks:
      - cloudingair-network
    depends_on:
      - discovery
      - dbmysql
    environment:
      - DATABASE_HOST=dbmysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=cloudingair
      - DATABASE_PORT=3306

  cloudingairmongo:
    container_name: cloudingair-airports
    build:
      context: ./cloudingair-mongo
      dockerfile: Dockerfile
    image: cloudingairmongo:latest
    expose:
      - "8081"
    networks:
      - cloudingair-network
    depends_on:
      - discovery
      - dbmongo

  discovery:
    container_name: cloudingair-eureka
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    image: discovery:latest
    ports:
      - 8761:8761
    networks:
      - cloudingair-network

  dbmysql:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - cloudingair-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cloudingair
      - MYSQL_PASSWORD=root
    restart: always

  dbmongo:
    image: mongo
    expose:
      - "27017"
    networks:
      - cloudingair-network
    volumes:
      - mongodata:/data/db

networks:
  cloudingair-network:
    driver: bridge
volumes:
  mysqldata:
  mongodata:
